### ISSUE TITLE
Start/end report (admin only)

### ISSUE THREAD

**Issue by Beyzary** [kolayne/anonymous_helpline_chatbot#11]
Report about start/end of conversation with operator designation to admin. Maybe should include rating of session (how?)
Rate may be:
- on a ten-point scale
- mood rate depending on the initial (worse/initial/better)

**Comment by kolayne** [comment]
Hi, @Beyzary, sorry for the delayed reply!
Are you saying admins rate sessions? I don't think you wanted to say that, and if you didn't, this is an absolutely separate issue from conversation start/end reporting.

**Comment by Beyzary** [comment]
@kolayne, only users can rate sessions ofc
