### ISSUE TITLE
The invitations sent before bot restart problem...

### ISSUE THREAD

**Issue by kolayne** [kolayne/anonymous_helpline_chatbot#32]
The current version of the bot has the following issue. All the invitation messages' ids are stored in the runtime variables instead of the database. That's why whenever the bot is restarted (for example, because of an update or because of an unhandled internal error) the invitation messages become undeletable. They aren't invalidated and operators still can join the conversations, but because the bot doesn't have the messages' ids, it is unable to delete them, so all the operators are likely to try to join the conversation.

I see two ways of solving this problem: either trying to handle the moment when the bot stops and removing the invitations at that moment (with warnings sent to users that something goes wrong and they'll have to request a conversation again), or moving the information about the invitation messages to the database. The second way, of course, provides a better user experience, however, it may be hard to implement, so the first solution can be used as a hotfix/workaround

**Comment by Beyzary** [comment]
It's good that this problem was identified before the first release :)

**Comment by kolayne** [comment]
Btw, the second solution doesn't seem hard to implement even with the requirement for logic.py to stay independent from `telebot`. We can use higher-order functions in logic, which would accept telebot-dependent invitations senders/deleters

**Comment by kolayne** [comment]
This turns to be a critical problem because operators can join the client via those preserved buttons
