### ISSUE TITLE
Handle entities in messages

### ISSUE THREAD

**Issue by kolayne** [kolayne/anonymous_helpline_chatbot#9]
The ideal way is to copy all the entities from the original message to the copied one. It will be easy to implement this with the Telegram Bots API 5.0 (with the `copyMessage` method), however, currently, there is no `telebot` release, supporting this API version.

For now, users should at least warned, that their formatting is lost and messages are forwarded as a plain text

**Comment by kolayne** [comment]
@Beyzary, do you think the priority of this issue can be reduced to medium if users will be notified that their entities are not parsed? Or is exactly _parsing_ entities high-priority?

**Comment by Beyzary** [comment]
@kolayne, okay

**Comment by kolayne** [comment]
A PR with the `copyMessage` method added has been merged to pyTelegramBotAPI. This should now be easy to implement

**Comment by kolayne** [comment]
Already fixed (together with #8)
